# Generated by Django 4.1.7 on 2023-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255, verbose_name='Date')),
                ('match', models.CharField(max_length=255, verbose_name='Match')),
                ('result', models.CharField(max_length=255, verbose_name='Result')),
                ('score', models.CharField(max_length=255, verbose_name='Score')),
                ('competition', models.CharField(max_length=255, verbose_name='Competition')),
            ],
        ),
    ]
